default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100

development:
  <<: *default
  uri: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  uri: <%= ENV['DATABASE_TEST_URL'] %>

production:
  <<: *default
  uri: <%= ENV['DATABASE_URL'] %>
